---
# See https://pre-commit.com for more information
# # See https://pre-commit.com/hooks.html for more hooks

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.3.0
      hooks:
          # General
          - id: check-added-large-files
          - id: check-case-conflict
          # - id: check-executables-have-shebangs
          # - id: check-json
          - id: check-merge-conflict
          # - id: check-toml
          # - id: check-xml
          # - id: check-yaml
          - id: detect-private-key
          - id: end-of-file-fixer
          - id: mixed-line-ending
          # - id: pretty-format-json
          #   args: [--autofix, --indent=4]
          # - id: sort-simple-yaml
          - id: trailing-whitespace
      # General
    - repo: meta
      hooks:
          - id: check-hooks-apply
          - id: check-useless-excludes
    - repo: https://github.com/codespell-project/codespell
      rev: v2.0.0
      hooks:
          - id: codespell
            args: [--ignore-words, .meta/codespell-ignores]
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: "v2.2.1"
      hooks:
          - id: prettier
            args: [--config, .meta/prettierrc.json]
    # - repo: https://github.com/adrienverge/yamllint
    #   rev: v1.24.2
    #   hooks:
    #       - id: yamllint
    #         args: [-c, .meta/yamllint.yaml]
