---
trigger:
    - "*"

resources:
    repositories:
        - repository: asottile
          type: github
          endpoint: github
          name: asottile/azure-pipeline-templates
          ref: refs/tags/v2.1.0

jobs:
    - template: job--pre-commit.yml@asottile
    - job: test
      steps:
          - task: DotNetCoreCLI@2
            inputs:
                command: "test"
