---
trigger:
    - "*"

resources:
    repositories:
        - repository: asottile
          type: github
          endpoint: github
          name: asottile/azure-pipeline-templates
          ref: refs/tags/v2.1.0

jobs:
    - template: job--pre-commit.yml@asottile
    - job: test
      steps:
          - task: DotNetCoreCLI@2
            inputs:
                command: "test"
    - job: publish
      displayName: Publish tagged releases
      condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
      dependsOn: [precommit, test]
      steps:
          - task: DotNetCoreCLI@2
            inputs:
                command: pack
                packagesToPack: ScopeGuard/ScopeGuard.csproj
                packDirectory: $(Build.ArtifactStagingDirectory)
                versioningScheme: "off"
                buildProperties: "-c Release"
          - task: DotNetCoreCLI@2
            inputs:
                command: "push"
                packagesToPush: "$(Build.ArtifactStagingDirectory)/*.nupkg"
                nuGetFeedType: "external"
                publishFeedCredentials: "Push Rkm.ScopeGuard from Azure Pipelines"
